project:
  type: website
  output-dir: docs
  resources:
    - images/

website:
  title: "Preston Rattle"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: resume.qmd
        text: Resume
      - href: post1.qmd
        text: "Post #1"

format:
  html:
    theme: theme.scss
    toc: false
    page-layout: article
    include-in-header: gtm-head.html
    include-before-body:
      - gtm-page-view.html
      - gtm-search-events.html
      - gtm-body.html
