project:
  type: website
  output-dir: docs

website:
  title: "Preston Rattle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: resume.qmd
        text: Resume
      - href: post1.qmd
        text: "Post #1"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    include-in-header: gtm-head.html
    include-before-body: gtm-body.html
