---
title: "Resume"
toc: true
toc-location: left
toc-title: "Contents"
---

- [LinkedIn](https://www.linkedin.com/in/prestonrattle/)
- [📄 Download resume PDF](resume.pdf)

### Experience

- **Global Digital - Analytics Manager**, Specialized Bicycle Components — Mar 2026 - Present
  - Guiding the analytics practice for Global Digital and Specialized more broadly.

- **Global Digital - Senior Data Analyst**, Specialized Bicycle Components — Oct 2022 - Mar 2026
  - Led analytics initiatives for the global digital business, supporting reporting, analysis, and insight generation across marketing, product, operations, finance, and executive leadership.
  - Partnered with technology & business leaders to design data solutions that give visibility into operational performance for major global initiatives.
  - Positioned Global Digital as a leader in data-driven operations, leading to requests for support & guidance across the organization.
  - Architected tracking for the global ecommerce site, designing the data layer and implementation across 30+ ecommerce-enabled countries.
  - Engineered product datasets using SQL & ETL tools, combining 10+ data sources, enabling end-to-end visibility into product movement from manufacturer to warehouse to customer.
  - Analyzed customers subscribed to marketing, finding they had +47% higher LTV than non-subscribed customers, so the business increased focus on growing subscriptions.
  - Reduced manual reporting by 50% across the Global Digital business, creating self-serve reports supported by robust documentation.
  - Identified $2M in annual revenue leakage from a global promotion change; presented analysis to Chief Digital Officer that led to reversal and recaptured revenue.
  - Connected online behavior to retail purchases by writing complex SQL that gave executive leadership insight into omnichannel customer journey for the first time.
  - Mentored junior analysts, supporting growth & advancing analytical output.

- **Global Ecommerce - Web Analyst**, Specialized Bicycle Components — Aug 2021 - Oct 2022
  - Educated teammates & stakeholders on best practices for using tools/reports & performing analysis.
  - Partnered with data engineers to create data models for new datasets.
  - Performed market research that informed the launch strategy of a new product offering.
  - Reduced OPEX by $100k annually for team by automating manual processes, allowing organization to simplify technology stack.

- **Digital Analyst**, Tinuiti — Sep 2020 - Jul 2021
  - Principal analyst for clients with annual revenue ranging from $100 million to $10 billion.
  - Designed plans to help businesses track & measure performance against their goals.
  - Created reusable analyses for the greater analytics department.
  - Guided marketing experiments to understand incrementality of spend.
  - Grew client accounts by partnering with account managers & junior analysts.

- **Associate Digital Analyst**, Tinuiti — Mar 2019 - Sep 2020
  - Based in Philadelphia, PA.

### Skills

- Story-based, outcome-focused analysis
- Data governance & documentation
- Data pipelines & modeling
- Advanced SQL (BigQuery, Redshift, Snowflake)
- Advanced Excel
- Advanced Tableau
- Intermediate R, Python, & JavaScript
- Advanced Google Tag Manager
- Web Analytics (e.g. Google Analytics)
- Marketing platforms (e.g. Google Ads, Klaviyo, DV360, Meta, etc.)
- Documentation & project management tools such as Jira & Confluence

### Education

- Major: Business Administration, University of Oregon — 2016
- Major: French, University of Oregon — 2016
- Minor: English, University of Oregon — 2016
- Business, Université Jean Moulin Lyon 3 — 2013
